version: '3.3'

services:
  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    container_name: wordpress
    ports: 
      - 8080:80
      - 443:443
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wpdb
    volumes:
      - ./wp-content:/var/www/html/wp-content

  db:
    image: mysql:8
    container_name: wp_mysql
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - 3333:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

